name: sensors_trial
description: A Flutter app to visualize motion and gravity sensors
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^3.0.2
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true